apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: helse-reverse-proxy
  namespace: default
  labels:
    team: dusseldorf
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - https://helse-reverse-proxy.nais.preprod.local
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: false
    path: /metrics
  vault:
    enabled: false
  env:
    - name: HRP_pleiepengesoknad_mottak
      value: http://pleiepengesoknad-mottak
    - name: HRP_omsorgspenger_mottak
      value: http://omsorgspenger-mottak
    - name: HRP_omsorgspengerutbetalingsoknad_mottak
      value: http://omsorgspengerutbetalingsoknad-mottak
    - name: HRP_k9_selvbetjening_oppslag
      value: http://k9-selvbetjening-oppslag
    - name: HRP_omsorgspengerutbetaling_mottak
      value: http://omsorgspengerutbetaling-mottak
    - name: HRP_k9_ettersending_mottak
      value: http://k9-ettersending-mottak
