apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: helse-reverse-proxy
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 1024Mi
  ingresses:
    - https://helse-reverse-proxy.nais.adeo.no
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: false
    path: /metrics
  vault:
    enabled: false
  env:
    - name: HRP_security_token_service
      value: http://security-token-service
    - name: HRP_aktoer_register
      value: https://app.adeo.no/aktoerregister
    - name: HRP_sparkel
      value: http://sparkel
    - name: HRP_pleiepengesoknad_prosessering
      value: http://pleiepengesoknad-prosessering